
export const CHANNEL_REPOSITORY = 'CHANNEL_REPOSITORY';
export const DATASET_REPOSITORY = 'DATASET_REPOSITORY';
export const DATASETKICK_REPOSITORY = 'DATASETKICK_REPOSITORY';
export const LIVESTREAM_REPOSITORY = 'LIVESTREAM_REPOSITORY';
export const PLATFORM_REPOSITORY = 'PLATFORM_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const VIDEOONDEMAND_REPOSITORY = 'VIDEOONDEMAND_REPOSITORY';
export const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
export const ANALYSIS_REPOSITORY = 'ANALYSIS_REPOSITORY';
